interface _TimeDurationExtensions
  def -: (Numeric other) -> Time
       | (Time other) -> Float
  def +: (Numeric other) -> Time
end

module TimeDurationExtensions : _TimeDurationExtensions
  def -: (Duration other) -> Time
  def +: (Duration other) -> Time
end

class Time
  prepend TimeDurationExtensions
end
