type number = Float | Rational | Integer

class Duration
  include Comparable

  MILLISECONDS: Integer
  SECONDS: Integer
  MINUTES: Integer
  HOURS: Integer
  DAYS: Integer

  TIME_NAMES: Hash[Integer, String]

  def initialize: (number amount, ?units: Integer units) -> Duration

  def days: () -> Rational
  def hours: () -> Rational
  def minutes: () -> Rational
  def seconds: () -> Rational
  def milliseconds: () -> Rational
  alias ms milliseconds

  def <=>: (Duration other) -> Integer
  def +: (Duration other) -> Duration
  def -: (Duration other) -> Duration
  def *: (number other) -> Duration
  def /: (number other) -> Duration
       | (Duration other) -> Rational
  def %: (Duration other) -> Duration

  def format: (?precision: Integer) -> String

  alias to_s format
end
