module DateTimeDurationExtensions
  def +: (Duration | number other) -> Date
  def -: (Duration | number other) -> Date
       | (DateTime other) -> number
end

class DateTime < Date
  prepend DateTimeDurationExtensions
end
