interface _TimeDurationExtensions
  def +: (Numeric other) -> Time
  def -: (Numeric other) -> Time
       | (Time other) -> Float
end

module TimeDurationExtensions : _TimeDurationExtensions
  def +: (Duration other) -> Time
       | ...
  def -: (Duration other) -> Time
       | ...
end

class Time
  prepend TimeDurationExtensions
end
