name: RSpec

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: bundle install
  rubocop:
    needs: build
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
    - name: Run tests
      run: bundle exec rake rubocop
  test:
    needs: build
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
    - name: Run tests
      run: bundle exec rake spec
